name: Pre-commit Linting & Checks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -Ls https://astral.sh/uv/install.sh | bash

        # Below Step is necessary to get the currently private usebench
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
        
        # Below is necessary due to some tests needing git 
      - name: Ensure git is installed & Configured
        run: |
          sudo apt-get update && sudo apt-get install -y git
          git config --global user.name "CI Bot"
          git config --global user.email "ci@example.com"

      - name: Set up virtualenv & install pre-commit
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
          uv pip install pre-commit

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
